# Generated by Django 5.1.3 on 2024-11-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TekshiruvKurinishi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Вид испытания')),
                ('measure', models.CharField(choices=[('kg', 'kg'), ('gr', 'gr'), ('m2', 'm2'), ('mg', 'mg'), ('m3', 'm3')], max_length=10, verbose_name='Единица измерения')),
                ('ammount', models.CharField(max_length=255, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Вид испытания',
                'verbose_name_plural': 'Виды испытания',
            },
        ),
        migrations.CreateModel(
            name='UlchovAsbob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование средств измерений и испытательных оборудований:')),
                ('ser', models.CharField(max_length=255, verbose_name='Наименование средств измерений и испытательных оборудований: Сертификаты поверки/калибровки или аттестации')),
            ],
            options={
                'verbose_name': "O'lchov asboblari / sertifikatlari",
                'verbose_name_plural': "O'lchov asboblari / sertifikatlari",
            },
        ),
        migrations.RemoveField(
            model_name='shartnoma',
            name='gost',
        ),
        migrations.RemoveField(
            model_name='shartnoma',
            name='parametr',
        ),
        migrations.RemoveField(
            model_name='shartnoma',
            name='sertifikatlash',
        ),
        migrations.RemoveField(
            model_name='shartnoma',
            name='sklad',
        ),
        migrations.RemoveField(
            model_name='shartnoma',
            name='tekshiruv_kurinishi',
        ),
        migrations.RemoveField(
            model_name='shartnoma',
            name='ulchov_asbob',
        ),
        migrations.AddField(
            model_name='shartnoma',
            name='gost',
            field=models.ManyToManyField(to='core.gost', verbose_name='Gost'),
        ),
        migrations.AddField(
            model_name='shartnoma',
            name='parametr',
            field=models.ManyToManyField(to='core.gostparametr', verbose_name='Gost parametr'),
        ),
        migrations.AddField(
            model_name='shartnoma',
            name='sertifikatlash',
            field=models.ManyToManyField(related_name='shartnoma_sertifikatlash', to='core.ulchovasbob', verbose_name='Сертификаты поверки/калибровки или аттестации'),
        ),
        migrations.AddField(
            model_name='shartnoma',
            name='sklad',
            field=models.ManyToManyField(to='core.sklad', verbose_name='Sklad'),
        ),
        migrations.AddField(
            model_name='shartnoma',
            name='tekshiruv_kurinishi',
            field=models.ManyToManyField(to='core.tekshiruvkurinishi', verbose_name='Вид испытания'),
        ),
        migrations.AddField(
            model_name='shartnoma',
            name='ulchov_asbob',
            field=models.ManyToManyField(related_name='shartnoma_ulchov_asbob', to='core.ulchovasbob', verbose_name='Наименование средств измерений и испытательных оборудований:'),
        ),
    ]
