# Generated by Django 5.1.3 on 2025-01-26 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tekshiruvkurinishi_ulchovasbob_remove_shartnoma_gost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': "Mijoz qo'shish", 'verbose_name_plural': "Mijozlarni qo'shish"},
        ),
        migrations.AlterModelOptions(
            name='clientproduct',
            options={'verbose_name': 'Mijoz maxsulotlari', 'verbose_name_plural': 'Mijozlar maxsuloti'},
        ),
        migrations.AlterModelOptions(
            name='gost',
            options={'verbose_name': 'Gost', 'verbose_name_plural': 'Gostlar'},
        ),
        migrations.AlterModelOptions(
            name='gostparametr',
            options={'verbose_name': 'Gost parametrlari', 'verbose_name_plural': 'Gost parametrlari'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Servis', 'verbose_name_plural': 'Servis xizmatlar'},
        ),
        migrations.AlterModelOptions(
            name='shartnoma',
            options={'verbose_name': 'Shartnoma', 'verbose_name_plural': 'Shartnomalar'},
        ),
        migrations.AlterModelOptions(
            name='sklad',
            options={'verbose_name': 'Ombor', 'verbose_name_plural': 'Omborxona'},
        ),
        migrations.AlterModelOptions(
            name='tekshiruvkurinishi',
            options={'verbose_name': 'Tekshiruv', 'verbose_name_plural': "Tekshiruv ko'rinishlari"},
        ),
    ]
