# Generated by Django 5.1.4 on 2025-02-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_client_certificate_alter_client_client_stir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='value',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('gr', 'Gram'), ('m2', 'Square Meter'), ('mg', 'Milligram'), ('m3', 'Cubic Meter')], default=1, max_length=50, verbose_name='Qiymatni tanlang'),
            preserve_default=False,
        ),
    ]
